# Generated by Django 5.1.1 on 2024-09-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url_page',
            field=models.URLField(blank=True, null=True),
        ),
    ]
